theme: jekyll-theme-cayman
title: "Maus cheiros de código em aplicativos Android: Um estudo sobre a percepção dos desenvolvedores"
description: Apêndice online do artigo submetido a conferência SBES 2017 (31st Brazilian Symposium on Software Engineering).